### ISSUE TITLE
Fix Lit Ref

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series5#4]
Hi @MFernflower @kwanchristopher the link to the lit ref we need on the wiki page should point at https://pubs.rsc.org/en/Content/ArticleLanding/RA/2014/C3RA46791K#!divAbstract rather than the PDF we've downloaded. Can someone please fix?

Also, that paper is not open access. We can't legally store it on Github. I've deleted it.

Can resolve this issue when link fixed.

**Comment by MFernflower** [comment]
I think we are good!
